service: AWSSelfLearning

provider:
  name: aws
  runtime: java8
  region: global
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:ListBucket
      Resource: "*"

package:
  artifact: build/libs/AWSSelfLearning.jar

functions:
  Lambda1:
    handler: lambda.Lambda1::handleRequest
    timeout: 900
    reservedConcurrency: 100
    events:
      - sns:
          arn: !Ref SuperTopic
          topicName: MyCustomTopic

  Lambda2:
    handler: lambda.Lambda2::handleRequest
    timeout: 900
    reservedConcurrency: 100

  Lambda3:
    handler: lambda.Lambda3::handleRequest
    timeout: 900
    reservedConcurrency: 100  #ReservedConcurrentExecutions(AWS)
    events:
      - schedule: cron(0 9 ? * 2#1 *) #cron(0/1 * ? * MON-FRI *)

resources:
  Resources:
    SuperTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: MyCustomTopic

    S3FromLambda1Cache:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "lambda1s3"
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"

    S3FromLambda2Cache:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "lambda2s3"
        CorsConfiguration:  #描述用于 Amazon S3 存储桶中对象的跨源访问配置
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"